#!/bin/bash
##############################################################################
# ESG Federation download script
#
# Template version: 1.2
# Generated by esg-dn1.nsc.liu.se - 2020/04/08 09:55:38
# Search URL: https://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.ps.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.ta.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.ua.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.hus.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrPlevPt.ts.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.va.gn.v20200218|noresg.nird.sigma2.no
#
###############################################################################
# first be sure it's bash... anything out of bash or sh will break
# and the test will assure we are not using sh instead of bash
if [ $BASH ] && [ `basename $BASH` != bash ]; then
    echo "######## This is a bash script! ##############" 
    echo "Change the execution bit 'chmod u+x $0' or start with 'bash $0' instead of sh."
    echo "Trying to recover automatically..."
    sleep 1
    /bin/bash $0 $@
    exit $?
fi

version=1.3.2
CACHE_FILE=.$(basename $0).status
openId=
search_url='https://esg-dn1.nsc.liu.se/esg-search/wget/?distrib=false&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.ps.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.ta.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.ua.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.hus.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrPlevPt.ts.gn.v20200218|noresg.nird.sigma2.no&dataset_id=CMIP6.ScenarioMIP.NCC.NorESM2-MM.ssp585.r1i1p1f1.6hrLev.va.gn.v20200218|noresg.nird.sigma2.no'

#These are the embedded files to be downloaded
download_files="$(cat <<EOF--dataset.file.url.chksum_type.chksum
'hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/hus/gn/v20200218/hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'SHA256' '7cfbd53c8850f5f0955c20a24978454b6242a779d849e92d4afca7d48a1ea8ca'
'hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/hus/gn/v20200218/hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'SHA256' 'e630d8102d3f8fa055a23d9baa250f1048a1ed876a622ce97d1582588db2a4b8'
'hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/hus/gn/v20200218/hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'SHA256' 'd6e03508cb73f40247eeede9564fb45b45e41938baf542cb910855e53073ed25'
'hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/hus/gn/v20200218/hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'SHA256' '49a2b7573fec58fc65a527ab184dfa5bb78ed6253e082a934fdb6ad298216ac7'
'hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/hus/gn/v20200218/hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'SHA256' '94783e30b233aa65e324e1f5f16ffc3b4c326c655daeff055df33085948a70ed'
'hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/hus/gn/v20200218/hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'SHA256' '63a9f5ca4bbeb0bd2977a2cea257a7c2b8a214f090f78a452731d019a4fb2c5e'
'hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/hus/gn/v20200218/hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'SHA256' 'e90a73f15abd65e4502caee39e0e64908085472a1fff383de6a34d07b2bb7be3'
'hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/hus/gn/v20200218/hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'SHA256' 'a66a6b0b849125dcd7a5c1f20e8d80bf21646e2539b2fadbc79b18e63a069383'
'hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/hus/gn/v20200218/hus_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'SHA256' '4b01ebcf177537d2d280d2461dec7d029766462785fc6758cfd3b37d889bf583'
'ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ps/gn/v20200218/ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'SHA256' '19386c24821855af9448c1679992c2653a999ae777570bee376d51e6026d8f3c'
'ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ps/gn/v20200218/ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'SHA256' 'fea7d0622fd5c3e80f5058827b57d249a8efa962b5c2c6d3c2da4787362e7e74'
'ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ps/gn/v20200218/ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'SHA256' 'e76f4d3c5db72030b3b97a614f608b7e368132c2e417cd8c91c2db93d5feb17c'
'ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ps/gn/v20200218/ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'SHA256' '01e50ff60c446b4c8c77383336cc978a0aeebe8386ae8ac96b6afb737d3f0ac0'
'ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ps/gn/v20200218/ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'SHA256' 'd6be988734f164624d53f66d90ce8b05cebd2f966e70e22edaed04a4b4ed5708'
'ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ps/gn/v20200218/ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'SHA256' 'e14162cc5308ef69a081f5fe06472dfad16563d84962ff7102c765542c0f4bbd'
'ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ps/gn/v20200218/ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'SHA256' '45fb00e46aad63bb8854e411689fb7cd35e5d2b4ae24729e579ff79772787364'
'ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ps/gn/v20200218/ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'SHA256' '0fee4a3b9e9519eb0cacb6db96a009b572a3957ff8535566fa15d2c21ee93d67'
'ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ps/gn/v20200218/ps_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'SHA256' 'e8ee34ccbb91ef33b5cb365d1dfb51dab8fd80c84e4b60069a2c98d59300f60c'
'ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ta/gn/v20200218/ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'SHA256' '4cf8fd9018ba918d4e4c56c3728c385efddeaa7e59b432e8778072f870cb40c0'
'ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ta/gn/v20200218/ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'SHA256' 'cceb7ebc729ab7eadd00eae1ebf6789ebf7ce6a67f8d4e56c1d0e6e8d5d4f3ae'
'ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ta/gn/v20200218/ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'SHA256' '6720cbe438087fb7b386ee3f7ec526a446e0327ce4d555d517e5b65672e5b5e5'
'ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ta/gn/v20200218/ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'SHA256' 'fce630521e04d1f73649d8624e8bbb2d171bb6d251802aa6fe5010153e0097d7'
'ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ta/gn/v20200218/ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'SHA256' '0a7a4124a1a49e9869b7357bea0700fbb1551f7a2cdcdb65f8d9798ac85f1e61'
'ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ta/gn/v20200218/ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'SHA256' '2d5e34b25ed90bf24f0ce144953d0f0b2d4dd61916da0f9ece6cdc4916d88bdc'
'ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ta/gn/v20200218/ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'SHA256' 'e16c41aeea8bb41f633d3745e4d6f2f9c6e5107c3636004f2956d61cfad097ab'
'ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ta/gn/v20200218/ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'SHA256' '782763d995a0dd243f53579ad806a04d1e646a3c3604d5348e1eed143e9bab4f'
'ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ta/gn/v20200218/ta_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'SHA256' '66459b39a2557accf91bf2018dadd939caa74a4956e79f2be0b46cbebef353d9'
'ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ua/gn/v20200218/ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'SHA256' '6082f337efc4aef82cb8234503259d1bd723b0ddf577f5cca340837293eb8972'
'ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ua/gn/v20200218/ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'SHA256' 'cd478154ac280e30fad8c64fcd7f7463040944216f2b5b6dd539b9685ebf60ce'
'ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ua/gn/v20200218/ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'SHA256' 'fc0f81bbcadeb1325b5b9f718572b2d66ad617c219f3cf2d1b9859fc5d7aed3b'
'ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ua/gn/v20200218/ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'SHA256' '1bb60dde40c80f93f3e971a4c139f878f3f262765f1d0fcc27c7d7d70d290b04'
'ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ua/gn/v20200218/ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'SHA256' '42fb0343b66927835434dd95f99ac0d54da7fbae6707bf181228b963fdc4e8ad'
'ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ua/gn/v20200218/ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'SHA256' 'f9d012c5f777077784505a1e74a875270a4c99b17cabbbad1d00668e84ae131a'
'ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ua/gn/v20200218/ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'SHA256' '8978eb36f5374f8cd444094087218b8491665778158f0d028d7156154a06834a'
'ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ua/gn/v20200218/ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'SHA256' '9a929d7435e68392693e369414648d2cd701f61817b506ac815726f4be360985'
'ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/ua/gn/v20200218/ua_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'SHA256' '20fa6b4dc2ef2a39804796b7c2649dff34311b9c0e13cf94b3a0db4bae70a1d5'
'va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/va/gn/v20200218/va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'SHA256' '7c8e161fe6825c05368bfb05fb6d6303329fe0e17b6c338cce78a9c250605e82'
'va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/va/gn/v20200218/va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'SHA256' 'fdc9380fef3f452530a7b69d6e2c3e26e795d6f599b24819a0bc0bc34897a196'
'va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/va/gn/v20200218/va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'SHA256' 'f698fba4dbdd96d57264c08fab4a61b9296ddfe92ceccfc034fdb6783d6d51c7'
'va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/va/gn/v20200218/va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'SHA256' '36a6f6905771986e9d08125ac48f2f405e3a20409da0b72e4f9238d2908a9633'
'va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/va/gn/v20200218/va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'SHA256' 'c9a624b585e31e44127501c1f8333a1e356011cb144a000b4f3c774f611ad431'
'va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/va/gn/v20200218/va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'SHA256' 'e04bdc05e6e7b010989b4281d582499e366c6e826c20ce4a55f3b61e355e33be'
'va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/va/gn/v20200218/va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'SHA256' 'd31cd396137775eedfe97bd6eb5afc8f01560954925115d84f73b46dcff4b751'
'va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/va/gn/v20200218/va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'SHA256' '65bbd2e147653bf6f4f64102041027b87cfda96f138e219257bae278c9416d12'
'va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrLev/va/gn/v20200218/va_6hrLev_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'SHA256' '53f21a37365b332349bf3bddc696b024736fb60a88870b14abde93e2d7e40c41'
'ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlevPt/ts/gn/v20200218/ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_201501010000-202101010000.nc' 'SHA256' '996f50714da84544e8210216c9b0f75c75f7d0f2de48028e4e9214a5fa5277db'
'ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlevPt/ts/gn/v20200218/ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_202101010600-203101010000.nc' 'SHA256' 'fef443853c3d8ec1e7f601e67d55aae628af3825bb945de4d50a0fae74f2db89'
'ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlevPt/ts/gn/v20200218/ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_203101010600-204101010000.nc' 'SHA256' 'ce09a3d23529bc00b5bbcd417ebcedd2b832f59fccce343a55d4f02e8ae309ff'
'ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlevPt/ts/gn/v20200218/ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_204101010600-205101010000.nc' 'SHA256' 'b069dc3697d5c25ff47fea8b2ba4a9bacd734581b1f457f47f1e1721ed7d39a2'
'ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlevPt/ts/gn/v20200218/ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_205101010600-206101010000.nc' 'SHA256' '0c356f4f1f8f62d84201c145722d4210a644bcd3c8c62e64ea5fd7fd690e771c'
'ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlevPt/ts/gn/v20200218/ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_206101010600-207101010000.nc' 'SHA256' '7d5a73266732ee8db498110d8cdd66d90374344e0d5f30df83888decb9b9531c'
'ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlevPt/ts/gn/v20200218/ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_207101010600-208101010000.nc' 'SHA256' '6086cc0d9ffdfd1242d6d0a541fb35920b40270324d6de8f6bb7fc046e996fdb'
'ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlevPt/ts/gn/v20200218/ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_208101010600-209101010000.nc' 'SHA256' '17147dd29c82afa6f5662a0d2dd791d8fb7bae33a5ee863101531f7cd9bb63ba'
'ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'http://noresg.nird.sigma2.no/thredds/fileServer/esg_dataroot/cmor/CMIP6/ScenarioMIP/NCC/NorESM2-MM/ssp585/r1i1p1f1/6hrPlevPt/ts/gn/v20200218/ts_6hrPlevPt_NorESM2-MM_ssp585_r1i1p1f1_gn_209101010600-210101010000.nc' 'SHA256' '57c8a02cedee8e6d609ca48abe7ace0ea1860bb147816238996b236493928d6f'
EOF--dataset.file.url.chksum_type.chksum
)"

# ESG_HOME should point to the directory containing ESG credentials.
#   Default is $HOME/.esg
ESG_HOME=${ESG_HOME:-$HOME/.esg}
[[ -d $ESG_HOME ]] || mkdir -p $ESG_HOME

ESG_CREDENTIALS=${X509_USER_PROXY:-$ESG_HOME/credentials.pem}
ESG_CERT_DIR=${X509_CERT_DIR:-$ESG_HOME/certificates}
MYPROXY_STATUS=$HOME/.MyProxyLogon
COOKIE_JAR=$ESG_HOME/cookies
MYPROXY_GETCERT=$ESG_HOME/getcert.jar
CERT_EXPIRATION_WARNING=$((60 * 60 * 8))   #Eight hour (in seconds)

WGET_TRUSTED_CERTIFICATES=$ESG_HOME/certificates


# Configure checking of server SSL certificates.
#   Disabling server certificate checking can resolve problems with myproxy
#   servers being out of sync with datanodes.
CHECK_SERVER_CERT=${CHECK_SERVER_CERT:-Yes}

check_os() {
    local os_name=$(uname | awk '{print $1}')
    case ${os_name} in
        Linux)
            ((debug)) && echo "Linux operating system detected"
            LINUX=1
            MACOSX=0
            ;;
        Darwin)
            ((debug)) && echo "Mac OS X operating system detected"
            LINUX=0
            MACOSX=1
            ;;
        *)
            echo "Unrecognized OS [${os_name}]"
            return 1
            ;;
    esac
    return 0
}

#taken from http://stackoverflow.com/a/4025065/1182464
vercomp () {
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

check_commands() {
    #check wget
    local MIN_WGET_VERSION=1.10
    vercomp $(wget -V | sed -n 's/^.* \([1-9]\.[0-9.]*\) .*$/\1/p') $MIN_WGET_VERSION
    case $? in
        2) #lower
            wget -V
            echo
            echo "** ERROR: wget version is too old. Use version $MIN_WGET_VERSION or greater. **" >&2
            exit 1
    esac
}

usage() {
    echo "Usage: $(basename $0) [flags] [openid] [username]"
    echo "Flags is one of:"
    sed -n '/^while getopts/,/^done/  s/^\([^)]*\)[^#]*#\(.*$\)/\1 \2/p' $0
    echo
    echo "This command stores the states of the downloads in .$0.status"
    echo "For more information check the website: http://esgf.org/wiki/ESGF_wget"
}

#defaults
debug=0
clean_work=1

#parse flags
while getopts ':c:pfF:o:w:isuUndvqhHI:T' OPT; do
    case $OPT in
        H) skip_security=1 && use_http_sec=1;; #       : Authenticate with OpenID (username,) and password, without the need for a certificate.
        T) force_TLSv1=1;;              #       : Forces wget to use TLSv1. 
        c) ESG_CREDENTIALS="$OPTARG";;  #<cert> : use this certificate for authentication.
        f) force=1;;                    #       : force certificate retrieval (defaults to only once per day); for certificate-less authentication (see -H option), this flag will force login and refresh cookies.
        F) input_file="$OPTARG";;       #<file> : read input from file instead of the embedded one (use - to read from stdin)
        o) openId="$OPTARG";;           #<openid>: Provide OpenID instead of interactively asking for it.
        I) username_supplied="$OPTARG";;    #<user_id> : Explicitly set user ID.  By default, the user ID is extracted from the last component of the OpenID URL.  Use this flag to override this behaviour.                   
        w) output="$OPTARG";;           #<file> : Write embedded files into a file and exit
        i) insecure=1;;                 #       : set insecure mode, i.e. don't check server certificate
        s) skip_security=1 && use_cookies_for_http_basic_auth_start=1;;            #       : completely skip security. It will only work if the accessed data is not secured at all. -- works only if the accessed data is unsecured or a certificate exists or cookies are saved (latter applies to -H option only).
        u) update=1;;                   #       : Issue the search again and see if something has changed.
        U) update_files=1;;             #       : Update files from server overwriting local ones (detect with -u)
        n) dry_run=1;;                  #       : Don't download any files, just report.
        p) clean_work=0;;               #       : preserve data that failed checksum
        d) verbose=1;debug=1;;          #       : display debug information
        v) verbose=1;;                  #       : be more verbose
        q) quiet=1;;                    #       : be less verbose
        h) usage && exit 0;;            #       : displays this help
        \?) echo "Unknown option '$OPTARG'" >&2 && usage && exit 1;;
        \:) echo "Missing parameter for flag '$OPTARG'" >&2 && usage && exit 1;;
    esac
done
shift $(($OPTIND - 1))

#setup input as desired by the user
if [[ "$input_file" ]]; then
    if [[ "$input_file" == '-' ]]; then
        download_files="$(cat)" #read from STDIN
        exec 0</dev/tty #reopen STDIN as cat closed it
    else
        download_files="$(cat $input_file)" #read from file
    fi
fi

#if -w (output) was selected write file and finish:
if [[ "$output" ]]; then
    #check the file
    if [[ -f "$output" ]]; then
        read -p "Overwrite existing file $output? (y/N) " answ
        case $answ in y|Y|yes|Yes);; *) echo "Aborting then..."; exit 0;; esac
    fi
    echo "$download_files">$output
    exit
fi


#assure we have everything we need
check_commands

if ((update)); then
    echo "Checking the server for changes..."
    new_wget="$(wget "$search_url" -qO -)"
    compare_cmd="grep -vE '^(# Generated by|# Search URL|search_url=)'"
    if diff -q <(eval $compare_cmd<<<"$new_wget") <(eval $compare_cmd $0) >/dev/null; then
        echo "No changes detected."
    else
        echo "Wget was changed. Dowloading. (old renamed to $0.old.#N)"
        counter=0
        while [[ -f $0.old.$counter ]]; do ((counter++)); done
        mv $0 $0.old.$counter
        echo "$new_wget" > $0
    fi
    exit 0      
fi


##############################################################################
check_java() {
    if ! type java >& /dev/null; then
        echo "Java could not be found." >&2
        return 1
    fi
    if java -version 2>&1|grep openjdk >/dev/null; then
        openjdk=1;
    else
        openjdk=0;
    fi
    jversion=($(jversion=$(java -version 2>&1 | awk '/version/ {gsub("\"","");print $3}'); echo ${jversion//./ }))
    mVer=${jversion[1]}
    if [ $openjdk -eq 1 ]; then
        mVer=${jversion[0]}
        if ((mVer<5)); then
            echo "Openjdk detected. Version 9+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    else
    
        if ((mVer<5)); then
            echo "Java version 1.5+ is required for retrieving the certificate." >&2
            echo "Current version seems older: $(java -version | head -n1) " >&2
            return 1
        fi
    fi
}

check_myproxy_logon() {
    if ! type myproxy-logon >& /dev/null; then
	echo "myproxy-logon could not be found." >&2
	return 1
    fi
    echo "myproxy-logon found" >&2
}

proxy_to_java() {
    local proxy_user proxy_pass proxy_server proxy_port
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$http_proxy)
    local JAVA_PROXY=
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttp.proxyPort=$proxy_port"
    eval $(sed 's#^\(https\?://\)\?\(\([^:@]*\)\(:\([^@]*\)\)\?@\)\?\([^:/]*\)\(:\([0-9]*\)\)\?.*#proxy_user=\3;proxy_pass=\5;proxy_server=\6;proxy_port=\8#'<<<$https_proxy)
    [[ "$proxy_server" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyHost=$proxy_server"
    [[ "$proxy_port" ]] && JAVA_PROXY=$JAVA_PROXY" -Dhttps.proxyPort=$proxy_port"
    
    echo "$JAVA_PROXY"
}

# get certificates from github
get_certificates() {
    # don't if this was already done today
    [[ -z $force && "$(find $ESG_CERT_DIR -type d -mtime -1 2>/dev/null)" ]] && return 0
    echo -n "Retrieving Federation Certificates..." >&2

    if ! wget -O $ESG_HOME/esg-truststore.ts --no-check-certificate https://github.com/ESGF/esgf-dist/raw/master/installer/certs/esg-truststore.ts; then
        echo "Could not fetch esg-truststore";
        return 1
    fi
    
    if ! wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar -O - -q | tar x -C $ESG_HOME; then
        #certificates tarred into esg_trusted_certificates. (if it breaks, let the user know why
        wget --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/esg_trusted_certificates.tar
        echo "Could't update certs!" >&2
        return 1
    else
        #if here everythng went fine. Replace old cert with this ones    
        [[ -d $ESG_CERT_DIR ]] && rm -r $ESG_CERT_DIR || mkdir -p $(dirname $ESG_CERT_DIR)
        mv $ESG_HOME/esg_trusted_certificates $ESG_CERT_DIR
        touch $ESG_CERT_DIR
        echo "done!" >&2
    fi

}

# Retrieve ESG credentials
unset pass
get_credentials() {
    if check_java
    then
	use_java=1
    else	
	use_java=0
	echo "No suitable java for obtaining certificate - checking for myproxy-logon instead" >&2
	check_myproxy_logon || exit 1
    fi
    #get all certificates
    get_certificates

    if [[ -z "$(find $MYPROXY_GETCERT -type f -mtime -1 2>/dev/null)" ]]; then
        echo -n "(Downloading $MYPROXY_GETCERT... "
        mkdir -p $(dirname $MYPROXY_GETCERT)
        if wget -q --no-check-certificate https://raw.githubusercontent.com/ESGF/esgf-dist/master/installer/certs/getcert.jar -O $MYPROXY_GETCERT;then
            echo 'done)'
            touch $MYPROXY_GETCERT
        else
            echo 'failed)'
        fi
    fi

    #if the user already defined one, use it
    if [[ -z $openId ]]; then
        #try to parse the last valid value if any
        [[ -f "$MYPROXY_STATUS" ]] && openId=$(awk -F= '/^OpenID/ {gsub("\\\\", ""); print $2}' $MYPROXY_STATUS)
        if [[ -z $openId ]]; then
            #no OpenID, we need to ask the user
            echo -n "Please give your OpenID (Example: https://myserver/example/username) ? "
        else
            #Allow the user to change it if desired
            echo -n "Please give your OpenID (hit ENTER to accept default: $openId)? "
        fi
        read -e
        [[ "$REPLY" ]] && openId="$REPLY"
    else
        ((verbose)) && echo "Using user defined OpenID $openId (to change use -o <open_id>)"
    fi

    if grep -q ceda.ac.uk <<<$openId; then
        username=${openId##*/}
        echo -n "Please give your username if different [$username]: "
        read -e
        [[ "$REPLY" ]] && username="$REPLY"
    fi
    


    if [ $use_java -eq 1 ]
    then
        local args=
        #get password
	[[ ! "$pass" ]] && read -sp "MyProxy Password? " pass
        [[ "$openId" ]] && args=$args" --oid $openId"
        [[ "$pass" ]] && args=$args" -P $pass"
        [[ "$username" ]] && args=$args" -l $username"
        
        echo -n $'\nRetrieving Credentials...' >&2
        if ! java $(proxy_to_java) -jar $MYPROXY_GETCERT $args --ca-directory $ESG_CERT_DIR --output $ESG_CREDENTIALS ; then        
            echo "Certificate could not be retrieved"
            exit 1
        fi
        echo "done!" >&2
    else
        args=`openid_to_myproxy_args $openId $username` || exit 1
        if ! myproxy-logon $args -b -o $ESG_CREDENTIALS
	then
            echo "Certificate could not be retrieved"
	    exit 1
        fi
	cp $HOME/.globus/certificates/* $ESG_CERT_DIR/	
    fi
}

openid_to_myproxy_args() {
  python - <<EOF || exit 1
import sys
import re
import xml.etree.ElementTree as ET
import urllib2
openid = "$1"
username = "$2" or re.sub(".*/", "", openid)
e = ET.parse(urllib2.urlopen(openid))
servs = [el for el in e.getiterator() if el.tag.endswith("Service")]
for serv in servs:
    servinfo = dict([(re.sub(".*}", "", c.tag), c.text)
                     for c in serv.getchildren()])
    try:
        if servinfo["Type"].endswith("myproxy-service"):
            m = re.match("socket://(.*):(.*)", servinfo["URI"])
            if m:
                host = m.group(1)
                port = m.group(2)
                print "-s %s -p %s -l %s" % (host, port, username)
                break
    except KeyError:
        continue
else:
    sys.stderr.write("myproxy service could not be found\n")
    sys.exit(1)
EOF
}

# check the certificate validity
check_cert() {
    if [[ ! -f "$ESG_CERT" || $force ]]; then
        #not there, just get it
        get_credentials
    elif which openssl &>/dev/null; then
        #check openssl and certificate
        if ! openssl x509 -checkend $CERT_EXPIRATION_WARNING -noout -in $ESG_CERT 2>/dev/null; then
            echo "The certificate expires in less than $((CERT_EXPIRATION_WARNING / 60 / 60)) hour(s). Renewing..."
            get_credentials
        else
            #ok, certificate is fine
            return 0
        fi
    fi
}

#
# Detect ESG credentials
#
find_credentials() {

    #is X509_USER_PROXY or $HOME/.esg/credential.pem
    if [[ -f "$ESG_CREDENTIALS" ]]; then
        # file found, proceed.
        ESG_CERT="$ESG_CREDENTIALS"
        ESG_KEY="$ESG_CREDENTIALS"
    elif [[ -f "$X509_USER_CERT" && -f "$X509_USER_KEY" ]]; then
        # second try, use these certificates.
        ESG_CERT="$X509_USER_CERT"
        ESG_KEY="$X509_USER_KEY"
    else
        # If credentials are not present, just point to where they should go 
        echo "No ESG Credentials found in $ESG_CREDENTIALS" >&2
            ESG_CERT="$ESG_CREDENTIALS"
            ESG_KEY="$ESG_CREDENTIALS"
            #they will be retrieved later one
    fi


    #chek openssl and certificate
    if (which openssl &>/dev/null); then
        if ( openssl version | grep 'OpenSSL 1\.0' ); then
            echo '** WARNING: ESGF Host certificate checking might not be compatible with OpenSSL 1.0+'
        fi
        check_cert || { (($?==1)); exit 1; }
    fi
    
    if [[ $CHECK_SERVER_CERT == "Yes" ]]; then
        [[ -d "$ESG_CERT_DIR" ]] || { echo "CA certs not found. Aborting."; exit 1; }
        PKI_WGET_OPTS="--ca-directory=$ESG_CERT_DIR"
    fi

    #some wget version complain if there's no file present
    [[ -f $COOKIE_JAR ]] || touch $COOKIE_JAR

    PKI_WGET_OPTS="$PKI_WGET_OPTS --certificate=$ESG_CERT --private-key=$ESG_KEY --save-cookies=$COOKIE_JAR --load-cookies=$COOKIE_JAR --ca-certificate=$ESG_CERT"

}

check_chksum() {
    local file="$1"
    local chk_type=$2
    local chk_value=$3
    local local_chksum=Unknown

    case $chk_type in
        md5) local_chksum=$(md5sum_ $file | cut -f1 -d" ");;
        sha256) local_chksum=$(sha256sum_ $file|awk '{print $1}'|cut -d ' ' -f1);;
        *) echo "Can't verify checksum." && return 0;;
    esac

    #verify
    ((debug)) && echo "local:$local_chksum vs remote:$chk_value" >&2
    echo $local_chksum
}

#Our own md5sum function call that takes into account machines that don't have md5sum but do have md5 (i.e. mac os x)
md5sum_() {
    hash -r
    if type md5sum >& /dev/null; then
        echo $(md5sum $@)
    else
        echo $(md5 $@ | sed -n 's/MD5[ ]*\(.*\)[^=]*=[ ]*\(.*$\)/\2 \1/p')
    fi
}

#Our own sha256sum function call that takes into account machines that don't have sha256sum but do have sha2 (i.e. mac os x)
sha256sum_() {
    hash -r
    if type sha256sum >& /dev/null; then
        echo $(sha256sum $@)
    elif type shasum >& /dev/null; then
        echo $(shasum -a 256 $@)
    else
        echo $(sha2 -q -256 $@)
    fi
}

get_mod_time_() {
    if ((MACOSX)); then
        #on a mac modtime is stat -f %m <file>
        echo "$(stat -f %m $@)"
    else
        #on linux (cygwin) modtime is stat -c %Y <file>
        echo "$(stat -c %Y $@)"
    fi
    return 0;
}

remove_from_cache() {
    local entry="$1"
    local tmp_file="$(grep -ve "^$entry" "$CACHE_FILE")"
    echo "$tmp_file" > "$CACHE_FILE"
    unset cached
}

#Download data from node using cookies and not certificates.
download_http_sec()
{
  #The data to be downloaded.
  data=" $url"
  filename="$file"  

  #Wget args.
  if ((insecure)) 
  then
   wget_args=" --no-check-certificate --cookies=on  --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt " 
  else
   wget_args=" --ca-directory=$WGET_TRUSTED_CERTIFICATES --cookies=on --keep-session-cookies --save-cookies $COOKIES_FOLDER/wcookies.txt "  
  fi 

  if ((use_cookies_for_http_basic_auth_start)) || ((use_cookies_for_http_basic_auth)) 
  then
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
  fi
  
  if((force_TLSv1))
  then
   wget_args=" $wget_args"" --secure-protocol=TLSv1 "
  fi
  
  
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
    wget_args="$wget_args $ESGF_WGET_OPTS"
  fi  
  

  #use cookies for the next downloads
  use_cookies_for_http_basic_auth=1;
   
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "wget $wget_args $data\n"
  fi


  #Try to download the data. 
  command="wget $wget_args -O $filename $data"
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
      
  #Extract orp service from url ?
  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" == 1 )) && 
  if  echo "$http_resp" | grep -q "/esg-orp/"      
  then
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   orp_service=$(echo "$urls" | tr '\n' ' ' | cut -d' ' -f 2)


   #Use cookies for transaction with orp.
   wget_args=" $wget_args"" --load-cookies $COOKIES_FOLDER/wcookies.txt"    
   
   #Download data using either http basic auth or http login form.
   if [[ "$openid_c" == */openid/  || "$openid_c" == */openid ]]
   then
    download_http_sec_open_id
   else
    download_http_sec_decide_service
   fi
  else  
   if    echo "$http_resp" | grep -q "401 Unauthorized"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || echo "$http_resp" | grep -q "Connection timed out."  \
      || echo "$http_resp" | grep -q "no-check-certificate"  \
      || (( $cmd_exit_status != 0 ))      
   then 
    echo "ERROR : http request to OpenID Relying Party service failed."
    failed=1
   fi
  fi
}


#Function that decides which implementaion of idp to use.
download_http_sec_decide_service()
{
  #find claimed id

  pos=$(echo "$openid_c" | egrep -o '/' | wc -l)
  username_c=$(echo "$openid_c"  | cut -d'/' -f "$(($pos + 1))")
  esgf_uri=$(echo "$openid_c" | egrep -o '/esgf-idp/openid/')

  host=$(echo "$openid_c"  | cut -d'/' -f 3)
  #test ceda first.

  if [[ -z "$esgf_uri" ]]
  then
   openid_c_tmp="https://""$host""/openid/"
  else
   openid_c_tmp="https://""$host""/esgf-idp/openid/" 
  fi

  command="wget "$openid_c_tmp" --no-check-certificate ${force_TLSv1:+--secure-protocol=TLSv1} -O-"
        
  if [[ ! -z "$ESGF_WGET_OPTS" ]]
  then
   command="$command $ESGF_WGET_OPTS"
  fi  
          
  #Debug message.
  if  ((debug))
  then
   echo -e "\nExecuting:\n"
   echo -e "$command\n"
  fi
            

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
  

  if    echo "$http_resp" | grep -q "[application/xrds+xml]"  \
     && echo "$http_resp" | grep -q "200 OK"  \
     && (( cmd_exit_status == 0 ))       
  then
   openid_c=$openid_c_tmp
   download_http_sec_open_id
  else
   if [[ -z "$esgf_uri" ]]
   then
    echo "ERROR : HTTP request to OpenID Relying Party service failed."
    failed=1
   else
   download_http_sec_cl_id
   fi
  fi
}


download_http_sec_retry()
{
  echo -e "\nRetrying....\n"
  #Retry in case that last redirect did not work, this happens with older version of wget.
  command="wget $wget_args $data"
      
  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi   
   
  http_resp=$(eval $command  2>&1) 
  cmd_exit_status="$?"

  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi
   
  if    echo "$http_resp" | grep -q "401 Unauthorized"  \
     || echo "$http_resp" | grep -q "403: Forbidden"  \
     || echo "$http_resp" | grep -q "Connection timed out."  \
     || echo "$http_resp" | grep -q "no-check-certificate"  \
     || (( $cmd_exit_status != 0 ))      
  then 
   echo -e "\nERROR : Retry failed.\n"
   #rm "$filename"
   failed=1
  fi #if retry failed.
}

#Function for downloading data using the claimed id.
download_http_sec_cl_id()
{
  #Http request for sending openid to the orp service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\"  $wget_args -O- https://$orp_service/esg-orp/j_spring_openid_security_check.htm "

  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "wget $command\n"
  fi 
  
  
  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"

  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 
    
  
  #Extract orp service from openid ?
  #Evaluate response.If redirected to idp service send the credentials.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( redirects == 2  )) && 
  if  echo "$http_resp" | grep -q "login.htm"  && (( cmd_exit_status == 0 ))   
  then 
  
   urls=$(echo "$http_resp" | egrep -o 'https://[^ ]+' | cut -d'/' -f 3)
   idp_service=$(echo "$urls"  | tr '\n' ' ' | cut -d' ' -f 2) 
      
   command="wget --post-data  password=\"$password_c\" $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$idp_service/esgf-idp/idp/login.htm"
   

   #Debug message.
   if  ((debug))
   then
    echo -e "Executing:\n"
    echo -e "wget $command\n"
   fi 

   #Execution of command.
   http_resp=$(eval $command  2>&1)
   cmd_exit_status="$?"
      
   if ((debug))
   then
    echo -e "\nHTTP response:\n $http_resp\n"
   fi 
        
   #Evaluate response. 
   #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
   #(( "$redirects" != 5 )) \ 
   if    echo "$http_resp" | grep -q "text/html"  \
      || echo "$http_resp" | grep -q "403: Forbidden"  \
      || (( cmd_exit_status != 0 ))        
   then 
    rm "$filename"
    download_http_sec_retry
   fi
 
  else
   echo "ERROR : HTTP request to OpenID Provider service failed."
   failed=1
  fi #if redirected to idp.  
}



download_http_sec_open_id()
{
  #Http request for sending openid to the orp web service.
  command="wget --post-data \"openid_identifier=$openid_c&rememberOpenid=on\" --header=\"esgf-idea-agent-type:basic_auth\" --http-user=\"$username_c\" --http-password=\"$password_c\"  $wget_args ${quiet:+-q} ${quiet:--v} -O $filename https://$orp_service/esg-orp/j_spring_openid_security_check.htm "


  #Debug message.
  if  ((debug))
  then
   echo -e "Executing:\n"
   echo -e "$command\n"
  fi 

  #Execution of command.
  http_resp=$(eval $command  2>&1)
  cmd_exit_status="$?"
  
  
  if ((debug))
  then
   echo -e "\nHTTP response:\n $http_resp\n"
  fi 

  #Evaluate response.
  #redirects=$(echo "$http_resp" | egrep -c ' 302 ')
  #(( "$redirects" != 7 )) ||
  if   echo "$http_resp" | grep -q "text/html"  ||  (( $cmd_exit_status != 0 ))   
  then
   rm "$filename"
   download_http_sec_retry     
  fi #if error during http basic authentication. 
  
}


download() {
    wget="wget ${insecure:+--no-check-certificate} ${quiet:+-q} ${quiet:--v} -c ${force_TLSv1:+--secure-protocol=TLSv1} $PKI_WGET_OPTS"
    
    while read line
    do
        # read csv here document into proper variables
        eval $(awk -F "' '" '{$0=substr($0,2,length($0)-2); $3=tolower($3); print "file=\""$1"\";url=\""$2"\";chksum_type=\""$3"\";chksum=\""$4"\""}' <(echo $line) )

        #Process the file
        echo -n "$file ..."

        #get the cached entry if any.
        cached="$(grep -e "^$file" "$CACHE_FILE")"
        
        #if we have the cache entry but no file, clean it.
        if [[ ! -f $file && "$cached" ]]; then
            #the file was removed, clean the cache
            remove_from_cache "$file"
            unset cached
        fi
        
        #check it wasn't modified
        if [[ -n "$cached" && "$(get_mod_time_ $file)" == $(echo "$cached" | cut -d ' ' -f2) ]]; then
                    if [[ "$chksum" == "$(echo "$cached" | cut -d ' ' -f3)" ]]; then
                echo "Already downloaded and verified"
                continue
            elif ((update_files)); then
                #user want's to overwrite newer files
                rm $file
                remove_from_cache "$file"
                unset cached
            else
                #file on server is different from what we have. 
                echo "WARNING: The remote file was changed (probably a new version is available). Use -U to Update/overwrite"
                continue
            fi
        fi
        unset chksum_err_value chksum_err_count
        
        while : ; do
            # (if we had the file size, we could check before trying to complete)
            echo "Downloading"
            [[ ! -d "$(dirname "$file")" ]] && mkdir -p "$(dirname "$file")"
            if ((dry_run)); then
                #all important info was already displayed, if in dry_run mode just abort
                #No status will be stored
                break
            else
                if ((use_http_sec))
                then
                 download_http_sec
                 if ((failed))
                 then
                  break
                 fi
                else
                 $wget -O "$file" $url || { failed=1; break; }  
                fi                
            fi

            #check if file is there
            if [[ -f $file ]]; then
                ((debug)) && echo file found
                if [[ ! "$chksum" ]]; then
                    echo "Checksum not provided, can't verify file integrity"
                    break
                fi
                result_chksum=$(check_chksum "$file" $chksum_type $chksum)
                if [[ "$result_chksum" != "$chksum" ]]; then
                    echo "  $chksum_type failed!"
                    if ((clean_work)); then
                        if !((chksum_err_count)); then
                                chksum_err_value=$result_chksum
                                chksum_err_count=2
                            elif ((checksum_err_count--)); then
                                if [[ "$result_chksum" != "$chksum_err_value" ]]; then
                                    #this is a real transmission problem
                                    chksum_err_value=$result_chksum
                                    chksum_err_count=2
                                fi
                            else
                                #ok if here we keep getting the same "different" checksum
                                echo "The file returns always a different checksum!"
                                echo "Contact the data owner to verify what is happening."
                                echo
                                sleep 1
                                break
                            fi
                        
                            rm $file
                            #try again
                            echo -n "  re-trying..."
                            continue
                    else
                            echo "  don't use -p or remove manually."
                    fi
                else
                    echo "  $chksum_type ok. done!"
                    echo "$file" $(get_mod_time_ "$file") $chksum >> $CACHE_FILE
                fi
            fi
            #done!
            break
        done
        
        if ((failed)); then
            echo "download failed"
            # most common failure is certificate expiration, so check this
            #if we have the pasword we can retrigger download
            ((!skip_security)) && [[ "$pass" ]] && check_cert
            unset failed
        fi
        
done <<<"$download_files"

}

dedup_cache_() {
    local file=${1:-${CACHE_FILE}}
    ((debug)) && echo "dedup'ing cache ${file} ..."
    local tmp=$(LC_ALL='C' sort  -r -k1,2 $file | awk '!($1 in a) {a[$1];print $0}' | sort -k2,2)
    ((DEBUG)) && echo "$tmp"
    echo "$tmp" > $file
    ((debug)) && echo "(cache dedup'ed)"
}

http_basic_auth_func_info_message()
{
  echo  "********************************************************************************"
  echo  "*                                                                              *"
  echo  "* Note that new functionality to allow authentication without the need for     *"
  echo  "* certificates is available with this version of the wget script.  To enable,  *"
  echo  "* use the \"-H\" option and enter your OpenID and password when prompted:        *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -H [options...]                                     *"
  echo  "*                                                                              *"
  echo  "* For a full description of the available options use the help option:         *"
  echo  "*                                                                              *"
  echo  "* $ "$(basename "$0")" -h                                                  *"
  echo  "*                                                                              *"
  echo  "********************************************************************************"
}

#
# MAIN
#

if ((!use_http_sec))
then 
 http_basic_auth_func_info_message
fi

echo "Running $(basename $0) version: $version"
((verbose)) && echo "we use other tools in here, don't try to user their proposed 'options' directly"
echo "Use $(basename $0) -h for help."$'\n'

((debug)) && cat<<EOF
** Debug info **
ESG_HOME=$ESG_HOME
ESG_CREDENTIALS=$ESG_CREDENTIALS
ESG_CERT_DIR=$ESG_CERT_DIR
** -- ** -- ** -- ** --

EOF


cat <<'EOF-MESSAGE'
Script created for 54 file(s)
(The count won't match if you manually edit this file!)



EOF-MESSAGE
sleep 1

check_os
((!skip_security)) && find_credentials

if ((use_http_sec))
then 
     
 if (( ! insecure))
 then 
  get_certificates
 fi

 #Cookies folder.
 COOKIES_FOLDER="$ESG_HOME/wget_cookies"
 
 if (( force ))
 then
  if [ -d $COOKIES_FOLDER ] 
  then
   rm -rf $COOKIES_FOLDER
  fi
 fi

 #Create cookies folder. 
 if [[ ! -d $COOKIES_FOLDER ]] 
 then
  mkdir $COOKIES_FOLDER
 fi
 
 if((! use_cookies_for_http_basic_auth_start))
 then

  #Read openid.
  if [[ ! -z "$openId" ]]
  then
   openid_c="$openId"
  elif ( (("$#" > 1)) || (("$#" == 1)) ) 
  then
   openid_c=$1
  else
   read -p    "Enter your openid : " openid_c
  fi
  
  
  #Read username.
  if [[ ! -z "$username_supplied" ]]
  then
   username_c="$username_supplied"
  elif (("$#" == 2))
  then
   username_c=$2
  elif [[ "$openid_c" == */openid/ || "$openid_c" == */openid ]]
  then
   read -p    "Enter username : " username_c
  fi
  
  #Read password.
  read -s -p "Enter password : " password_c
  echo -e "\n"

 fi #use cookies

fi #use_http_sec 


#do we have old results? Create the file if not
[ ! -f $CACHE_FILE ] && echo "#filename mtime checksum" > $CACHE_FILE && chmod 666 $CACHE_FILE

#clean the force parameter if here (at htis point we already have the certificate)
unset force

download

dedup_cache_


echo "done"
